####### OP KINGDOMS CORE #######

# Special Event Date
Day: Sunday
# Time in 24 Hour format
Time: 12

# Event Reminder
Dragon_Event_Reminder: "&6%hour% hour and %minutes% mins remain until the dragon event starts"

# Event message
Dragon_Event_Message: "&6Ancient Dragon Event is Starting!!"

# Event End Message
Dragon_End_Event_Message: "&6The Ancient Black Dragon has been defeated!!"

# Commands for winners:
Dragon_Killer:
  Reward_1:
    Reward: "give %player_name% apple"
    Message: "&61 Apple"
  Reward_2:
    Reward: "give %player_name% iron_ingot 64"
    Message: "&664 iron"
First_Place_Rewards:
  Reward_1:
    Reward: "give %player_name% apple"
    Message: "&61 apple"
  Reward_2:
    Reward: "give %player_name% iron_ingot 64"
    Message: "&664 iron"
Second_Place_Rewards:
  Reward_1:
    Reward: "give %player_name% apple"
    Message: "&61 apple"
Third_Place_Rewards:
  Reward_1:
    Reward: "give %player_name% apple"
    Message: "&61 apple"
Damage_To_Level_Message: "&6%level% Levels!!"

# Teleport Delay in seconds.
Dragon_End_Event_Command_Delay: 30
# List of Commands, this will run after a delay from killing the dragon
Dragon_End_Event_Commands:
  - "cmi warp spawn %player_name%"
  - "playsound minecraft:ui.toast.challenge_complete player %player_name%"
  - "cmi titlemsg %player_name% Victory"

