name: OPKingdomsCore
version: ${project.version}
main: me.peepersoak.opkingdomscore.OPKingdomsCore
api-version: 1.17
authors: [ Peepersoak ]
description: A special events plugin for OP Kingdoms
commands:
  opkingdoms:
